apiVersion: v1
kind: Namespace
metadata:
  name: production

---
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
 name: pesbuk-prod
 namespace: production
spec:
 acme:
   # The ACME server URL
   server: https://acme-v02.api.letsencrypt.org/directory
   # Email address used for ACME registration
   email: kerupuk.lovers@gmail.com
   # Name of a secret used to store the ACME account private key
   privateKeySecretRef:
     name: pesbuk-prod
   # Enable the HTTP-01 challenge provider
   solvers:
   - selector: {}
     http01:
       ingress:
         class:  nginx

---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: production
type: Opaque
data:
   DB_USER: ZGV2b3BzY2lsc3k=
   DB_PASS: MTIzNDU2Nzg5MA==
   DB_HOST: a3ViZS1wZXNidWsuYzg0NXIzOXppYWFoLnVzLWVhc3QtMS5yZHMuYW1hem9uYXdzLmNvbQ==
   DB_NAME: ZGJzb3NtZWQ=

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      name: nginx
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers:
      - name: nginx
        image: raxer/pesbuk2
        env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: DB_PASS
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: DB_NAME
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: production
spec:
  #type: LoadBalancer
  ports:
    - port: 80
      #nodePort: 30080
  selector:
    name: nginx
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: production
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "pesbuk-prod"
spec:
  rules:
  - host: pesbuk.rafifauz.site
    http:
      paths:
      #- path: /belajar
      - backend:
          serviceName: nginx
          servicePort: 80
  
  tls:
  - hosts:
    - pesbuk.rafifauz.site
    secretName: pesbuk-tls

        
