apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
   DB_USER: ZGV2b3BzY2lsc3k=
   DB_PASS: MTIzNDU2Nzg5MA==
   DB_HOST: a3ViZS1wZXNidWsuY2N5Ym1pa2V6cG1jLmFwLXNvdXRoZWFzdC0xLnJkcy5hbWF6b25hd3MuY29t
   DB_NAME: ZGJzb3NtZWQ=

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers:
      - name: nginx
        image: raxer/pesbuk2
        env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: DB_PASS
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: DB_NAME
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30080
  selector:
    name: nginx



        
