apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel
spec:
  replicas: 3
  selector:
    matchLabels:
      name: laravel
  template:
    metadata:
      labels:
        name: laravel
    spec:
      containers:
      - name: laravel
        image: raxer/laravel
---
apiVersion: v1
kind: Service
metadata:
  name: laravel
spec:
  #type: LoadBalancer
  ports:
    - port: 8080
      #nodePort: 30080
  selector:
    name: laravel
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: laravel-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: lara.rafifauz.site
    http:
      paths:
      #- path: /belajar
      - backend:
          serviceName: laravel
          servicePort: 8080
