apiVersion: v1
kind: Secret
metadata:
  name: jssecret
type: Opaque
data:
   DB_USER: ZGV2b3BzY2lsc3k=
   DB_PASS: MTIzNDU2Nzg5MA==
   DB_HOST: a3ViZS1wZXNidWsuY2N5Ym1pa2V6cG1jLmFwLXNvdXRoZWFzdC0xLnJkcy5hbWF6b25hd3MuY29t
   DB_NAME: ZGJzb3NtZWQ=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nodejs
  template:
    metadata:
      labels:
        name: nodejs
    spec:
      containers:
      - name: nodejs
        image: raxer/nodejs-api2
        env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: jssecret
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: jssecret
                  key: DB_PASS
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: jssecret
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: jssecret
                  key: DB_NAME
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs
spec:
  type: NodePort
  ports:
  	- targetPort: 3000
      port: 3000
      nodePort: 30030
  selector:
    name: nodejs

