apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
   DB_USER: d29yZHByZXNzdXNlcg==
   DB_PASS: cGFzc3dvcmQ=
   DB_HOST: a3ViZS13b3JkcHJlc3MuY2N5Ym1pa2V6cG1jLmFwLXNvdXRoZWFzdC0xLnJkcy5hbWF6b25hd3MuY29t
   DB_NAME: d29yZHByZXNz
