apiVersion: v1
kind: Namespace
metadata:
  name: pesbuk-ns

---
apiVersion: v1
kind: Secret
metadata:
  name: wp-secret
  namespace: pesbuk-ns
type: Opaque
data:
   DB_USER: d29yZHByZXNzdXNlcg==
   DB_PASS: cGFzc3dvcmQ=
   DB_HOST: a3ViZS13b3JkcHJlc3MyLmM4NDVyMzl6aWFhaC51cy1lYXN0LTEucmRzLmFtYXpvbmF3cy5jb20=
   DB_NAME: d29yZHByZXNz

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: pesbuk-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      name: wordpress
  template:
    metadata:
      labels:
        name: wordpress
    spec:
      containers:
      - name: wordpress
        image: raxer/wordpress2
        env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: wp-secret
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: wp-secret
                  key: DB_PASS
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: wp-secret
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: wp-secret
                  key: DB_NAME
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: pesbuk-ns
spec:
  #type: LoadBalancer
  ports:
    - port: 80
      #nodePort: 30080
  selector:
    name: wordpress
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: pesbuk-ns
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: wordpress.rafifauz.site
    http:
      paths:
      #- path: /belajar
      - backend:
          serviceName: wordpress
          servicePort: 80


        
