apiVersion: v1
kind: Namespace
metadata:
  name: production

---
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
 name: wordpress-prod
 namespace: production
spec:
 acme:
   # The ACME server URL
   server: https://acme-v02.api.letsencrypt.org/directory
   # Email address used for ACME registration
   email: kerupuk.lovers@gmail.com
   # Name of a secret used to store the ACME account private key
   privateKeySecretRef:
     name: wordpress-prod
   # Enable the HTTP-01 challenge provider
   solvers:
   - selector: {}
     http01:
       ingress:
         class:  nginx
---
apiVersion: v1
kind: Secret
metadata:
  name: wp-secret
  namespace: production
type: Opaque
data:
   DB_USER: d29yZHByZXNzdXNlcg==
   DB_PASS: cGFzc3dvcmQ=
   DB_HOST: a3ViZS13b3JkcHJlc3MyLmM4NDVyMzl6aWFhaC51cy1lYXN0LTEucmRzLmFtYXpvbmF3cy5jb20=
   DB_NAME: d29yZHByZXNz

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      name: wordpress
  template:
    metadata:
      labels:
        name: wordpress
    spec:
      containers:
      - name: wordpress
        image: raxer/wordpress2
        env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: wp-secret
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: wp-secret
                  key: DB_PASS
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: wp-secret
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: wp-secret
                  key: DB_NAME
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: production
spec:
  #type: LoadBalancer
  ports:
    - port: 82
      #nodePort: 30080
  selector:
    name: wordpress
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wordpress-ingress
  namespace: production
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "wordpress-prod"
spec:
  rules:
  - host: wordpress.rafifauz.site
    http:
      paths:
      #- path: /belajar
      - backend:
          serviceName: wordpress
          servicePort: 82
  
  tls:
  - hosts:
    - wordpress.rafifauz.site
    secretName: wordpress-tls


        
