apiVersion: v1
kind: Secret
metadata:
  name: wp-secret
type: Opaque
data:
   DB_USER: d29yZHByZXNzdXNlcg==
   DB_PASS: cGFzc3dvcmQ=
   DB_HOST: a3ViZS13b3JkcHJlc3MuY2N5Ym1pa2V6cG1jLmFwLXNvdXRoZWFzdC0xLnJkcy5hbWF6b25hd3MuY29t
   DB_NAME: d29yZHByZXNz

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      name: wordpress
  template:
    metadata:
      labels:
        name: wordpress
    spec:
      containers:
      - name: wordpress
        image: raxer/wordpress2
        env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: wp-secret
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: wp-secret
                  key: DB_PASS
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: wp-secret
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: wp-secret
                  key: DB_NAME
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30081
  selector:
    name: wordpress



        
